@startuml 抽象クラスの例
abstract 照明器具 {
    {abstract} + 照明開始()
    {abstract} + 照明停止()
}

class 白熱電球 {
    + 照明開始()
    + 照明停止()
}

class 蛍光電球 {
    + 照明開始()
    + 照明停止()
}

class LED電球 {
    + 照明開始()
    + 照明停止()
}

class スイッチ {
    + ON()
    + OFF()
}

照明器具 <|-- 白熱電球
照明器具 <|-- 蛍光電球
照明器具 <|-- LED電球
スイッチ .> 照明器具
@enduml