@startuml 継承の例
class 商品 {
    # 商品コード
    # 商品名
    # 価格
    + 商品コードを取得する()
    + 商品名を取得する()
    + 価格を取得する()
}

class 携帯電話 {
    - 液晶サイズ
    + 液晶サイズを取得する()
}

class デジカメ {
    - 画素数
    + 画素数を取得する()
}

商品 <|-- 携帯電話
商品 <|-- デジカメ
@enduml