@startuml 分析クラス図・設計クラス図の例
left to right direction

class 社員 {
    氏名
    ログインする()
    経費を登録する()
    経費を申請する()
}

class 部署 {
    部署名
}

class 会社 {
    会社名
}

社員 "1..*" -- "1" 部署 : 所属する
部署 "1..*" -- "1" 会社
@enduml
