@startuml パッケージ図の例

package 研究部門 {
    
    class 会計担当 {
        + 研究費を処理する()
    }

    class 研究担当 {
        + 研究する()
    }
}

package 開発部門 {
    
    class 会計担当 {
        + 開発費を処理する()
    }

    class 開発担当 {
        + 開発する()
    }
}

package 研究開発部門 {}

研究部門 ..> 研究開発部門 : <<merge>>
開発部門 ..> 研究開発部門 : <<merge>>
@enduml