@startuml シーケンス図の例
participant ": ブラウザ" as ブラウザ
participant ": ウェブサーバ" as ウェブサーバ
participant ": データファイル" as データファイル

par
    ブラウザ -> ウェブサーバ : ページを表示する()
    ウェブサーバ -> データファイル : データを取得する()
else
    ブラウザ -> ウェブサーバ : データを送信する()
    ウェブサーバ -> データファイル : データを登録する()
end
@enduml
