@startuml シーケンス図の例
actor ": 送り主" as 送り主
participant ": チャットクライアント" as チャットクライアント
participant ": チャットサーバ" as チャットサーバ

group loop
    送り主 ->> チャットクライアント : テキストを入力する(テキスト)
    送り主 ->> チャットクライアント : 送信ボタンを押す()
    チャットクライアント ->> チャットサーバ : テキストを送信する(テキスト)
    チャットクライアント ->> チャットクライアント : 画面を更新する()
    チャットクライアント ->> チャットクライアント : メッセージを待機する()
end
@enduml
