@startuml オルタナティブの例
participant ": 貸出画面" as 貸出画面
participant ": 蔵書管理" as 蔵書管理
participant ": 蔵書リスト" as 蔵書リスト
participant "情報システム : 蔵書" as 情報システム

activate 貸出画面
貸出画面 -> 蔵書管理 : 貸出する(蔵書番号=1234, 貸出期間="2週間")
activate 蔵書管理
蔵書管理 -> 蔵書リスト : 書名 = 蔵書を取得する(1234) : 情報システム
activate 蔵書リスト
deactivate 蔵書リスト
蔵書管理 -> 情報システム : 貸出状況 = 貸出中か調べる()
activate 情報システム
deactivate 情報システム
蔵書管理 -> 情報システム : 発行日 = 発行日を取得する()
activate 情報システム
deactivate 情報システム

alt 貸出状況=="貸出中"
    蔵書管理 -> 蔵書管理 : エラーを通知する("貸出中")
else 発行日から1年経過していない
    蔵書管理 -> 蔵書管理 : エラーを通知する("貸出期間が長すぎます中")
else
    蔵書管理 -> 情報システム : 貸出状況を変更する("貸出中")
    activate 情報システム
    deactivate 情報システム
end
@enduml
