@startuml ステートマシン図の例1
left to right direction
note "上蓋が開いているときや\n水位が基準未満の時に\n加熱動作をしていない状態" as note1
[*] --> 待機中
待機中 --> 湯沸し中 : 湯沸しボタン押下\n[水位が基準以上かつ上蓋が閉じている]
湯沸し中 --> 待機中 : 上蓋が開いた
湯沸し中 --> 待機中 : 水位変化\n[水位が基準未満]
湯沸し中 : entry / 湯沸しランプを点灯する
湯沸し中 : do / 湯を沸かす
湯沸し中 : exit / 湯沸しランプを消灯する
保温中 --> 待機中 : 上蓋が開いた
保温中 --> 待機中 : 水位変化\n[水位が基準未満]
保温中 --> 湯沸し中 : 湯沸しボタン押下\n[水位が基準以上]
湯沸し中 --> 保温中 : 湯沸し完了
待機中 -> note1
待機中 --> [*] : 電源OFF
湯沸し中 --> [*] : 電源OFF
保温中 --> [*] : 電源OFF
@enduml
