@startuml ステートマシン図の例2
left to right direction

[*] --> 待機中

state 動作中 {
    [*] --> 湯沸し中
    湯沸し中 --> 保温中 : 湯沸し完了
    保温中 --> 湯沸し中 : 湯沸しボタン押下\n[水位が基準以上]
}

待機中 --> 動作中 : 湯沸しボタン押下\n[水位が基準以上かつ上蓋が閉じている]
動作中 --> 待機中 : 水位変化\n[水位が基準未満]
動作中 --> [*]
@enduml