@startuml UMLの実践例: ユースケース図
left to right direction

actor 登録済ユーザ

rectangle 社内SNSシステム {
    usecase アカウント情報を登録する
    usecase アカウント情報を変更する
    usecase 友達申請をする
    usecase 友達申請を承認する
    usecase "ユーザを検索・表示する"
    usecase 日記を投稿する
    usecase 日記を読む
    usecase 日記にコメントする

    登録済ユーザ -- アカウント情報を変更する
    登録済ユーザ -- 友達申請をする
    登録済ユーザ -- 友達申請を承認する
    登録済ユーザ -- "ユーザを検索・表示する"
    登録済ユーザ -- 日記を投稿する
    登録済ユーザ -- 日記を読む
    登録済ユーザ -- 日記にコメントする
}

@enduml
