@startuml UMLの実践例: 概念モデルのクラス図

class ユーザ {
    氏名
    メールアドレス
    パスワード
}

class 友達申請 {
    申請日
    友達になった日
}

class 投稿 {
    作成日
    投稿内容
    公開範囲
}

class タイムライン

ユーザ "*" -- "*" ユーザ : 友達申請する
(ユーザ, ユーザ) .. 友達申請
ユーザ "1" - "1" タイムライン
ユーザ "1" -- "*" 投稿
タイムライン "1..*" --- "*" 投稿

@enduml
