@startuml UMLの実践例: アクティビティ図

|ユーザ|
start
:「日記の投稿」を選択する;
|システム|
repeat
    :「日記の投稿入力画面」を表示する;
    |ユーザ|
    :投稿内容と公開範囲を入力する;
    :「内容確認」を選択する;
    |システム|
    :投稿内容の文字数制限を確認する;
    |ユーザ|
    :投稿内容と公開範囲について「修正」か「確定」かを選択する;
repeat while () is ([修正]) not ([確定])
|システム|
:日記の投稿内容を確定する;
:「日記の投稿表示画面」を表示する;
stop

@enduml
