@startuml UMLの実践例: 分析モデルのクラス図

class ユーザ <<entity>> {
    氏名
    メールアドレス
    パスワード
}

class 友達申請 {
    申請日
    友達になった日
}

class 投稿 <<entity>> {
    作成日
    投稿内容
    公開範囲
    作成する(投稿内容, 公開範囲)
}

class 日記 <<entity>> {}

class コメント <<entity>> {}

class タイムライン <<entity>> {}

ユーザ "*" -- "*" ユーザ : 友達申請する
(ユーザ, ユーザ) .. 友達申請
ユーザ "1" - "1" タイムライン
ユーザ "1" -- "*" 投稿
タイムライン "1..*" --- "*" 投稿
投稿 <|-- 日記
投稿 <|-- コメント
日記 "1" - "*" コメント

@enduml
